---
# tasks file for nginx
- name: Ensure nginx is at the latest version
  become: yes
  apt: 
    name: nginx 
    state: latest

# Nginx setup.
- name: Copy nginx configuration in place.
  become: yes
  template:
    src: custom_site.conf.j2 
    dest: /etc/nginx/sites-available/custom_site.conf 

- name: Symlink config 
  become: yes
  file:
    src: /etc/nginx/sites-available/custom_site.conf
    dest: /etc/nginx/sites-enabled/custom_site.conf
    state: link

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
