---
# tasks file for users
#

- name: Create groups
  become: yes
  block:
    - name: Create system groups
      group:
        name: "{{ item }}"
      with_items:
        - staff

- name: Allow staff group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%staff'
    line: '%staff ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: CRUD user accounts
  become: yes
  user:
    name: "{{ item.name }}"
    state: "{{ item.state|default('absent') }}"
    groups: "{{ ['staff'] + item.groups|default([]) }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    uid: "{{ item.uid|default(2000) }}"
  with_items: "{{ users }}"

- name: Manage public keys
  become: yes
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', item.1) }}"
  when: item.0.state == 'present'
  loop: "{{ lookup('subelements', users, 'authorized', {'skip_missing': True}, wantlist=True) }}"
