---
# tasks file for common
- name: Ensure ubuntu is set as a host 
  become: yes
  lineinfile:
    path: /etc/hosts 
    regexp: '^127\.0\.0\.1.*ubuntu'
    line: "127.0.0.1  ubuntu"

- name: Install git
  become: yes
  apt:
    name: git 
    state: latest
- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ git_username }}" }
    - {name: "user.email", value: "{{ git_email }}" }

- name: Install curl
  become: yes
  apt:
    name: curl 
    state: latest