---
# tasks file for wireguard
#
- name: Install gpg 
  become: yes
  apt:
    name: gpg 
    state: present

# TODO: This was an issue with docker/molecule and may not be an issue later
- name: Install drmngr 
  become: yes
  apt:
    update_cache: yes
    name: dirmngr 
    state: present

- name: Install software properties
  become: yes
  apt:
    name: software-properties-common 
    state: present

- name: Add wireguard repo 
  become: yes
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install linux headers
  become: yes
  package:
    name: "linux-headers-{{ ansible_kernel }}"
  tags:
    - skip_docker

- name: Install resolvconf 
  become: yes
  apt:
    update_cache: yes
    name: resolvconf
    state: present
  register: result 
  until: result is not failed
  retries: 5
  delay: 30
  tags:
    - skip_docker

- name: Install wireguard and iptables 
  become: yes
  apt:
    update_cache: yes
    name: ['wireguard', 'iptables'] 
    state: present

- name: Ensure wireguard conf dir exists 
  become: yes
  file:
    path: /etc/wireguard
    mode: '644'
    state: directory

- name: Generate server private key 
  command: "wg genkey"
  register: priv_key_out
- set_fact: 
    priv_key={{ priv_key_out.stdout }}

- name: Generate server public key 
  shell: 'echo {{ priv_key }} | wg pubkey'
  register: pub_key_out
- set_fact: 
    pub_key={{ pub_key_out.stdout }}

#
# Client vars that get used to define a client in the interface config
#
- name: Generate client private key 
  command: "wg genkey"
  register: priv_key_out
- set_fact: 
    client_priv_key={{ priv_key_out.stdout }}

- name: Generate client public key 
  shell: 'echo {{ client_priv_key }} | wg pubkey'
  register: pub_key_out
- set_fact: 
    client_pub_key={{ pub_key_out.stdout }}
#
#
#

- name: Generate symm pre key 
  command: "wg genpsk"
  register: symm_key_out
- set_fact: 
    symm_key={{ symm_key_out.stdout }}

- name: Add wireguard params 
  become: yes
  template:
    src: params.j2
    dest: /etc/wireguard/params
    mode: '0644'

- name: Add wireguard interface
  become: yes
  template:
    src: interface.conf.j2
    dest: "/etc/wireguard/{{ wg_server.interface_name }}.conf"
    mode: '0644'

- name: Enable port forward ipv4 systctl.d/wg.conf
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    sysctl_file: /etc/sysctl.d/wg.conf
    reload: yes
  tags:
    - skip_docker

- name: Enable port forward ipv6 systctl.d/wg.conf
  become: yes
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    sysctl_file: /etc/sysctl.d/wg.conf
    reload: yes
  tags:
    - skip_docker

# 
# Generate and save client file
#
- name: Create client file 
  become: yes
  template:
    src: client.conf.j2
    dest: "/etc/wireguard/{{ wg_server.interface_name }}-client-{{ wg_client.name }}.conf"
    mode: '0644'

- name: Enable and start wg service 
  become: yes
  systemd:
    name: "wg-quick@{{ wg_server.interface_name }}"
    state: started
    enabled: yes
  tags:
    - skip_docker
